# Site settings
title: The Art of HFT to AI
email: noeveah@gmail.com
description: >-
  This site is my homepage blog of techs.

url: "https://qingchaomeng.github.io"
baseurl: ""

markdown: kramdown

# Build settings
theme: minima
plugins:
  - jekyll-feed
